In [3]:
import numpy as np

In [30]:
rng = np.random.default_rng()

matrix1 = rng.integers(low=0, high= 100,size=(2,3))
matrix2 = rng.integers(low=0, high= 100,size=(3,2))
print("mat1")
print(matrix1)
print("mat2")
print(matrix2)

mat1
[[59  0 80]
 [11 75 78]]
mat2
[[ 9 58]
 [72 88]
 [68 25]]


In [35]:
x = np.dot(matrix2,matrix1)
print(x)

[[ 1169  4350  5244]
 [ 5216  6600 12624]
 [ 4287  1875  7390]]


In [41]:
matA = rng.integers(0,101, size=(3,3))
matB = rng.integers(0,101, size=(3,3))
print(matA)
mmp = matA*matB
print(mmp)

[[50 16 55]
 [ 3 67 26]
 [68 92  3]]
[[4350 1232 3740]
 [ 183 3551 2002]
 [2312 7268    6]]


In [44]:
transposeA = matA.T
print(transposeA)

[[50  3 68]
 [16 67 92]
 [55 26  3]]


In [47]:
det_A = np.linalg.det(matA)
print(det_A)

-316805.99999999994


In [52]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2],[3,4],[5,6]])

det_a = np.linalg.det(a)
print(det_a)

0.0


In [59]:
try:
    inva = np.linalg.inv(matA)
    print(inva)
except np.linalg.LinAlgError:
    print("matrix is singular and dose't have an inverse")
    

[[ 0.0069159  -0.01582041  0.01031862]
 [-0.00555229  0.01133186  0.00358263]
 [ 0.01350985  0.01108565 -0.01042278]]


In [64]:
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [66]:
some1 = np.array([[2,1],[1,2]])
eigenvalues, eigenvectors = np.linalg.eig(some1)

print(eigenvalues)
print(eigenvectors)

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
